JDetmar/NLog.Extensions.AzureStorage

- src/NLog.Extensions.AzureStorage/BlobStorageTarget.cs
- src/NLog.Extensions.AzureStorage/NLog.Extensions.AzureStorage.csproj
Resolves #9 and resolves #10 (Bugs introduced with #7)
> Fixed NETSTANDARD define, and ensure InitializeContainer

- src/NLog.Extensions.AzureStorage/NLogEntity.cs
- src/NLog.Extensions.AzureStorage/TableStorageTarget.cs
Reverts JDetmar/NLog.Extensions.AzureStorage#13
> Revert "Add property for setting the LogTimeStamp format string. Also set the…"

- src/NLog.Extensions.AzureStorage/BlobStorageTarget.cs
- src/NLog.Extensions.AzureStorage/QueueStorageTarget.cs
- src/NLog.Extensions.AzureStorage/TableStorageTarget.cs
> Perform Exists check before CreateIfNotExists to avoid too much noise

- src/NLog.Extensions.AzureStorage/BlobStorageTarget.cs
- StringBuilder - Skips ToString-allocation
- String - Skips String.ToCharArray-allocation (and newline append)
> BlobStorageTarget - Reduce memory allocation by reusing encoding buffer

- src/NLog.Extensions.AzureStorage/TableStorageTarget.cs
@JDetmar 
Please review my pull request for one fix for DynamicTableEntity.
I modify DynamicTableEntity to be used in method Write(LogEventInfo logEvent) insead of NLogEntity.
> Fix DynamicTableEntity

- appveyor.yml
- src/NLog.Extensions.AzureEventHub.Tests/EventHubService.cs
- src/NLog.Extensions.AzureEventHub.Tests/EventHubTargetTest.cs
- src/NLog.Extensions.AzureEventHub.Tests/NLog.Extensions.AzureEventHub.Tests.csproj
- src/NLog.Extensions.AzureEventHub/EventHubTarget.cs
- src/NLog.Extensions.AzureEventHub/IEventHubService.cs
- src/NLog.Extensions.AzureEventHub/NLog.Extensions.AzureEventHub.csproj
- src/NLog.Extensions.AzureEventHub/Properties/AssemblyInfo.cs
- src/NLog.Extensions.AzureStorage.IntegrationTest/App.config
- src/NLog.Extensions.AzureStorage.IntegrationTest/NLog.Extensions.AzureStorage.IntegrationTest.csproj
- src/NLog.Extensions.AzureStorage.IntegrationTest/packages.config
- src/NLog.Extensions.AzureStorage.sln
- src/NLog.Extensions.AzureStorage/NLog.Extensions.AzureStorage.csproj
@JDetmar It compiles. Unit tests are green. But have no Azure Cloud to actual test if it works :)
> NLog.Extensions.AzureEventHub - Initial Version

- README.md
- src/NLog.Extensions.AzureCosmosTable/NLog.Extensions.AzureCosmosTable.csproj
> Updated Readme.md with links to updated nuget-packages

- src/NLog.Extensions.AzureBlobStorage/BlobStorageTarget.cs
> Fixed NullReferenceException in CloudBlobService

- src/NLog.Extensions.AzureBlobStorage/BlobStorageTarget.cs
- src/NLog.Extensions.AzureBlobStorage/NLog.Extensions.AzureBlobStorage.csproj
Since AppendFromByteArrayAsync is for single-writer scenario. Resolves #56
> BlobStorageTarget - Changed to AppendBlockAsync

- appveyor.yml
- src/NLog.Extensions.AzureAccessToken/AccessTokenLayoutRenderer.cs
- src/NLog.Extensions.AzureAccessToken/NLog.Extensions.AzureAccessToken.csproj
- src/NLog.Extensions.AzureAccessToken/Properties/AssemblyInfo.cs
- src/NLog.Extensions.AzureStorage.sln
- test/NLog.Extensions.AzureAccessToken.Tests/AccessTokenLayoutRendererTests.cs
- test/NLog.Extensions.AzureAccessToken.Tests/AzureServiceTokenProviderMock.cs
- test/NLog.Extensions.AzureAccessToken.Tests/NLog.Extensions.AzureAccessToken.Tests.csproj
@JDetmar Would you consider adding this nuget-package to the collection of Azure-packages?
> NLog.Extensions.AzureAccessToken - Application authentication for AccessToken

- src/NLog.Extensions.AzureAccessToken/AccessTokenLayoutRenderer.cs
Ensure two concurrent threads will only initialize a single AzureServiceTokenProvider
> AzureAccessToken - Reduce chance of race-conditions when initializing

- README.md
- src/NLog.Extensions.AzureAccessToken/README.md
- src/NLog.Extensions.AzureBlobStorage/BlobStorageTarget.cs
- src/NLog.Extensions.AzureBlobStorage/README.md
- src/NLog.Extensions.AzureCosmosTable/README.md
- src/NLog.Extensions.AzureCosmosTable/TableStorageTarget.cs
- src/NLog.Extensions.AzureEventHub/EventHubTarget.cs
- src/NLog.Extensions.AzureEventHub/README.md
- src/NLog.Extensions.AzureQueueStorage/README.md
Can see docs here:
https://github.com/snakefoot/NLog.Extensions.AzureStorage
> NLog.Extensions.AzureAccessToken - Split docs into multiple files

- README.md
- src/NLog.Extensions.AzureBlobStorage/NLog.Extensions.AzureBlobStorage.csproj
- src/NLog.Extensions.AzureCosmosTable/ICloudTableService.cs
- src/NLog.Extensions.AzureCosmosTable/NLog.Extensions.AzureCosmosTable.csproj
- src/NLog.Extensions.AzureCosmosTable/NLogEntity.cs
- src/NLog.Extensions.AzureCosmosTable/TableStorageTarget.cs
- src/NLog.Extensions.AzureStorage/ConnectionStringHelper.cs
> TableStorageTarget - Reduced required framework to net45

- src/NLog.Extensions.AzureCosmosTable/NLog.Extensions.AzureCosmosTable.csproj
- src/NLog.Extensions.AzureEventHub/NLog.Extensions.AzureEventHub.csproj
Table Storage: https://github.com/Azure/azure-cosmos-table-dotnet/issues/43
EventHubs: https://www.nuget.org/packages/Microsoft.Azure.EventHubs/
>  TableStorageTarget and  EventHubTarget with dependency update

- src/NLog.Extensions.AzureAccessToken/NLog.Extensions.AzureAccessToken.csproj
Microsoft.Azure.Services.AppAuthentication ver. 1.5.0  (Bug fixes)
> AzureAccessToken- Updated dependency AppAuthentication ver. 1.5.0 

- src/NLog.Extensions.AzureEventHub/EventHubTarget.cs
- src/NLog.Extensions.AzureEventHub/NLog.Extensions.AzureEventHub.csproj
- src/NLog.Extensions.AzureEventHub/README.md
> EventHubTarget - Make the calculated batchsize more conservative

- README.md
- src/NLog.Extensions.AzureAccessToken/NLog.Extensions.AzureAccessToken.csproj
- src/NLog.Extensions.AzureBlobStorage/NLog.Extensions.AzureBlobStorage.csproj
- src/NLog.Extensions.AzureBlobStorage/README.md
- src/NLog.Extensions.AzureQueueStorage/README.md
And some minor updates to documentation.
> AzureAccessToken - AppAuthentication ver. 1.6.0

- README.md
- src/NLog.Extensions.AzureEventHub/EventHubTarget.cs
- src/NLog.Extensions.AzureEventHub/NLog.Extensions.AzureEventHub.csproj
- src/NLog.Extensions.AzureEventHub/README.md
- src/NLog.Extensions.AzureServiceBus/ICloudServiceBus.cs
- src/NLog.Extensions.AzureServiceBus/NLog.Extensions.AzureServiceBus.csproj
- src/NLog.Extensions.AzureServiceBus/Properties/AssemblyInfo.cs
- src/NLog.Extensions.AzureServiceBus/README.md
- src/NLog.Extensions.AzureServiceBus/ServiceBusTarget.cs
- src/NLog.Extensions.AzureStorage.sln
- test/NLog.Extensions.AzureServiceBus.Tests/NLog.Extensions.AzureServiceBus.Tests.csproj
- test/NLog.Extensions.AzureServiceBus.Tests/ServiceBusMock.cs
- test/NLog.Extensions.AzureServiceBus.Tests/ServiceBusTargetTest.cs
API for Service Bus Queues is very similar to Event Hub DataStreams.
> NLog.Extensions.AzureServiceBus - Initial commit

- appveyor.yml
- src/NLog.Extensions.AzureCosmosTable/NLog.Extensions.AzureCosmosTable.csproj
- src/NLog.Extensions.AzureCosmosTable/TableStorageTarget.cs
- src/NLog.Extensions.AzureEventHub/EventHubTarget.cs
- src/NLog.Extensions.AzureEventHub/NLog.Extensions.AzureEventHub.csproj
- src/NLog.Extensions.AzureServiceBus/NLog.Extensions.AzureServiceBus.csproj
- src/NLog.Extensions.AzureServiceBus/README.md
- src/NLog.Extensions.AzureServiceBus/ServiceBusTarget.cs
- test/NLog.Extensions.AzureCosmosTable.Tests/CloudTableServiceMock.cs
- test/NLog.Extensions.AzureEventHub.Tests/EventHubServiceMock.cs
- test/NLog.Extensions.AzureEventHub.Tests/EventHubTargetTest.cs
- test/NLog.Extensions.AzureQueueStorage.Tests/CloudQueueServiceMock.cs
- test/NLog.Extensions.AzureServiceBus.Tests/ServiceBusMock.cs
Resolves #85
- Fixes bug in EventHubTarget
- Fixes bug in TableStorageTarget
- Fixes bug in ServiceBusTarget (Not yet released)
Version 3.0 is waiting for [Azure.Messaging.ServiceBus](https://www.nuget.org/packages/Azure.Messaging.ServiceBus/)
> Fixed bug in Flush when using BatchSize larger than 100

- appveyor.yml
Added ContinuousIntegrationBuild=true and EmbedUntrackedSources=true and PublishRepositoryUrl=true
Replaces #69
> Enable sourcelink and deterministic builds

- appveyor.yml
- src/NLog.Extensions.AzureAccessToken/NLog.Extensions.AzureAccessToken.csproj
- src/NLog.Extensions.AzureBlobStorage/NLog.Extensions.AzureBlobStorage.csproj
- src/NLog.Extensions.AzureCosmosTable/NLog.Extensions.AzureCosmosTable.csproj
- src/NLog.Extensions.AzureEventHub/EventHubTarget.cs
- src/NLog.Extensions.AzureEventHub/NLog.Extensions.AzureEventHub.csproj
- src/NLog.Extensions.AzureQueueStorage/NLog.Extensions.AzureQueueStorage.csproj
- src/NLog.Extensions.AzureServiceBus/NLog.Extensions.AzureServiceBus.csproj
ServiceBus has the concept UserProperty + SystemProperty. Align EventHub-Target with ServiceBus-Target.
> EventHubTarget - Actual support for userproperty to match ServiceBus

- src/NLog.Extensions.AzureBlobStorage/BlobStorageTarget.cs
- src/NLog.Extensions.AzureCosmosTable/TableStorageTarget.cs
- src/NLog.Extensions.AzureEventHub/EventHubTarget.cs
- src/NLog.Extensions.AzureEventHub/IEventHubService.cs
- src/NLog.Extensions.AzureEventHub/NLog.Extensions.AzureEventHub.csproj
- src/NLog.Extensions.AzureEventHub/README.md
- src/NLog.Extensions.AzureServiceBus/README.md
- src/NLog.Extensions.AzureServiceBus/ServiceBusTarget.cs
- src/NLog.Extensions.AzureStorage/SortHelpers.cs
- test/NLog.Extensions.AzureEventHub.Tests/EventHubServiceMock.cs
I guess someone should volunteer to test if the new version of `NLog.Extensions.AzureEventHub.3.0.0.nupkg` is working :)
Nuget-packages: https://ci.appveyor.com/project/JDetmar/nlog-extensions-azurestorage/builds/39978672/artifacts
> Changed to Azure.Messaging.EventHubs ver. 5.5.0

- appveyor.yml
- src/NLog.Extensions.AzureDataTables/DataTablesTarget.cs
- src/NLog.Extensions.AzureDataTables/ICloudTableService.cs
- src/NLog.Extensions.AzureDataTables/NLog.Extensions.AzureDataTables.csproj
- src/NLog.Extensions.AzureDataTables/NLogEntity.cs
- src/NLog.Extensions.AzureDataTables/Properties/AssemblyInfo.cs
- src/NLog.Extensions.AzureDataTables/README.md
- src/NLog.Extensions.AzureStorage.sln
- test/NLog.Extensions.AzureDataTables.Tests/CloudTableServiceMock.cs
- test/NLog.Extensions.AzureDataTables.Tests/DataTablesTargetTests.cs
- test/NLog.Extensions.AzureDataTables.Tests/NLog.Extensions.AzureDataTables.Tests.csproj
Replacing `NLog.Extensions.AzureCosmosTable`
> NLog.Extensions.AzureDataTables - Using new API Azure.Data.Tables

- src/NLog.Extensions.AzureDataTables/DataTablesTarget.cs
- src/NLog.Extensions.AzureDataTables/NLog.Extensions.AzureDataTables.csproj
Also improved NLog InternalLogger output for better diagnostics.
> AzureDataTables - Fixed bug where it failed to write when table already exists

- src/NLog.Extensions.AzureAccessToken/AccessTokenLayoutRenderer.cs
- src/NLog.Extensions.AzureBlobStorage/BlobStorageTarget.cs
- src/NLog.Extensions.AzureBlobStorage/ICloudBlobService.cs
- src/NLog.Extensions.AzureBlobStorage/NLog.Extensions.AzureBlobStorage.csproj
- src/NLog.Extensions.AzureBlobStorage/README.md
- src/NLog.Extensions.AzureDataTables/DataTablesTarget.cs
- src/NLog.Extensions.AzureDataTables/ICloudTableService.cs
- src/NLog.Extensions.AzureDataTables/NLog.Extensions.AzureDataTables.csproj
- src/NLog.Extensions.AzureDataTables/README.md
- src/NLog.Extensions.AzureEventHub/EventHubTarget.cs
- src/NLog.Extensions.AzureEventHub/IEventHubService.cs
- src/NLog.Extensions.AzureEventHub/NLog.Extensions.AzureEventHub.csproj
- src/NLog.Extensions.AzureEventHub/README.md
- src/NLog.Extensions.AzureQueueStorage/ICloudQueueService.cs
- src/NLog.Extensions.AzureQueueStorage/NLog.Extensions.AzureQueueStorage.csproj
- src/NLog.Extensions.AzureQueueStorage/QueueStorageTarget.cs
- src/NLog.Extensions.AzureQueueStorage/README.md
- src/NLog.Extensions.AzureServiceBus/ICloudServiceBus.cs
- src/NLog.Extensions.AzureServiceBus/NLog.Extensions.AzureServiceBus.csproj
- src/NLog.Extensions.AzureServiceBus/README.md
- src/NLog.Extensions.AzureServiceBus/ServiceBusTarget.cs
- test/NLog.Extensions.AzureBlobStorage.Tests/CloudBlobServiceMock.cs
- test/NLog.Extensions.AzureDataTables.Tests/CloudTableServiceMock.cs
- test/NLog.Extensions.AzureEventHub.Tests/EventHubServiceMock.cs
- test/NLog.Extensions.AzureQueueStorage.Tests/CloudQueueServiceMock.cs
- test/NLog.Extensions.AzureServiceBus.Tests/ServiceBusMock.cs
Work-around until Azure.Identity ver. 1.6 is ready, then it can be replaced with #120
> Added support for ClientIdentity with AzureServiceTokenProvider

- README.md
- appveyor.yml
- src/NLog.Extensions.AzureEventGrid/EventGridTarget.cs
- src/NLog.Extensions.AzureEventGrid/IEventGridService.cs
- src/NLog.Extensions.AzureEventGrid/NLog.Extensions.AzureEventGrid.csproj
- src/NLog.Extensions.AzureEventGrid/Properties/AssemblyInfo.cs
- src/NLog.Extensions.AzureEventGrid/README.md
- src/NLog.Extensions.AzureEventHub/EventHubTarget.cs
- src/NLog.Extensions.AzureServiceBus/ServiceBusTarget.cs
- src/NLog.Extensions.AzureStorage.sln
- test/NLog.Extensions.AzureEventGrid.Tests/EventGridServiceMock.cs
- test/NLog.Extensions.AzureEventGrid.Tests/EventGridTargetTest.cs
- test/NLog.Extensions.AzureEventGrid.Tests/NLog.Extensions.AzureEventGrid.Tests.csproj
See also: https://learn.microsoft.com/en-us/azure/event-grid/compare-messaging-services
Service | Purpose | Type | When to use
-- | -- | -- | --
Event Grid | Reactive programming | Event distribution (discrete) | React to status changes
Event Hubs | Big data pipeline | Event streaming (series) | Telemetry and distributed data streaming
Service Bus | High-value enterprise messaging | Message | Order processing and financial transactions
Seems batching is seldom used for "Event Grid" as it requires the receiver to also keep up.
https://ci.appveyor.com/project/JDetmar/nlog-extensions-azurestorage/builds/45346675/artifacts
> Introduced NLog.Extensions.AzureEventGrid

- src/NLog.Extensions.AzureBlobStorage/BlobStorageTarget.cs
- src/NLog.Extensions.AzureBlobStorage/NLog.Extensions.AzureBlobStorage.csproj
- src/NLog.Extensions.AzureDataTables/DataTablesTarget.cs
- src/NLog.Extensions.AzureDataTables/NLog.Extensions.AzureDataTables.csproj
- src/NLog.Extensions.AzureEventHub/EventHubTarget.cs
- src/NLog.Extensions.AzureEventHub/NLog.Extensions.AzureEventHub.csproj
- src/NLog.Extensions.AzureQueueStorage/NLog.Extensions.AzureQueueStorage.csproj
- src/NLog.Extensions.AzureQueueStorage/QueueStorageTarget.cs
- src/NLog.Extensions.AzureServiceBus/NLog.Extensions.AzureServiceBus.csproj
- src/NLog.Extensions.AzureServiceBus/ServiceBusTarget.cs
- test/NLog.Extensions.AzureAccessToken.Tests/NLog.Extensions.AzureAccessToken.Tests.csproj
- test/NLog.Extensions.AzureBlobStorage.Tests/NLog.Extensions.AzureBlobStorage.Tests.csproj
- test/NLog.Extensions.AzureDataTables.Tests/NLog.Extensions.AzureDataTables.Tests.csproj
- test/NLog.Extensions.AzureEventHub.Tests/NLog.Extensions.AzureEventHub.Tests.csproj
- test/NLog.Extensions.AzureQueueStorage.Tests/NLog.Extensions.AzureQueueStorage.Tests.csproj
- test/NLog.Extensions.AzureServiceBus.Tests/NLog.Extensions.AzureServiceBus.Tests.csproj
> Updated to Azure.Identity v1.8.2 and removed ResourceIdentity default value

- src/NLog.Extensions.AzureBlobStorage/NLog.Extensions.AzureBlobStorage.csproj
- src/NLog.Extensions.AzureDataTables/NLog.Extensions.AzureDataTables.csproj
- src/NLog.Extensions.AzureEventGrid/EventGridTarget.cs
- src/NLog.Extensions.AzureEventGrid/NLog.Extensions.AzureEventGrid.csproj
- src/NLog.Extensions.AzureEventGrid/README.md
- src/NLog.Extensions.AzureEventHub/NLog.Extensions.AzureEventHub.csproj
- src/NLog.Extensions.AzureQueueStorage/NLog.Extensions.AzureQueueStorage.csproj
- src/NLog.Extensions.AzureServiceBus/NLog.Extensions.AzureServiceBus.csproj
[Azure.Identity ver. 1.10.1](https://www.nuget.org/packages/Azure.Identity/1.10.1) has been marked as insecure.
>This package has at least one vulnerability with high severity. It may lead to specific problems in your project. Try updating the package version. 
> 
> Advisory: https://github.com/advisories/GHSA-5mfx-4wcx-rv27 | CVE-2023-36414 | Severity: high
> Ver. 4.3.1 - Dependency update with various bugfixes

- src/NLog.Extensions.AzureEventHub/EventHubTarget.cs
- src/NLog.Extensions.AzureEventHub/IEventHubService.cs
- src/NLog.Extensions.AzureEventHub/NLog.Extensions.AzureEventHub.csproj
- src/NLog.Extensions.AzureEventHub/README.md
- src/NLog.Extensions.AzureServiceBus/ICloudServiceBus.cs
- src/NLog.Extensions.AzureServiceBus/NLog.Extensions.AzureServiceBus.csproj
- src/NLog.Extensions.AzureServiceBus/README.md
- src/NLog.Extensions.AzureServiceBus/ServiceBusTarget.cs
- test/NLog.Extensions.AzureEventHub.Tests/EventHubServiceMock.cs
- test/NLog.Extensions.AzureServiceBus.Tests/ServiceBusMock.cs
Trying to resolve #152
- Added option UseWebSockets (true / false)
- Added option WebSocketProxyAddress (Uri)
- Added option CustomEndpointAddress (Uri)
> Added support for AmqpWebSockets

- src/NLog.Extensions.AzureAccessToken/NLog.Extensions.AzureAccessToken.csproj
- src/NLog.Extensions.AzureBlobStorage/NLog.Extensions.AzureBlobStorage.csproj
- src/NLog.Extensions.AzureDataTables/NLog.Extensions.AzureDataTables.csproj
- src/NLog.Extensions.AzureEventGrid/NLog.Extensions.AzureEventGrid.csproj
- src/NLog.Extensions.AzureEventHub/NLog.Extensions.AzureEventHub.csproj
- src/NLog.Extensions.AzureQueueStorage/NLog.Extensions.AzureQueueStorage.csproj
- src/NLog.Extensions.AzureServiceBus/NLog.Extensions.AzureServiceBus.csproj
- test/NLog.Extensions.AzureAccessToken.Tests/NLog.Extensions.AzureAccessToken.Tests.csproj
- test/NLog.Extensions.AzureBlobStorage.Tests/NLog.Extensions.AzureBlobStorage.Tests.csproj
- test/NLog.Extensions.AzureDataTables.Tests/NLog.Extensions.AzureDataTables.Tests.csproj
- test/NLog.Extensions.AzureEventGrid.Tests/NLog.Extensions.AzureEventGrid.Tests.csproj
- test/NLog.Extensions.AzureEventHub.Tests/NLog.Extensions.AzureEventHub.Tests.csproj
- test/NLog.Extensions.AzureQueueStorage.Tests/NLog.Extensions.AzureQueueStorage.Tests.csproj
- test/NLog.Extensions.AzureServiceBus.Tests/NLog.Extensions.AzureServiceBus.Tests.csproj
- [CVE-2024-29992](https://github.com/advisories/GHSA-wvxc-855f-jvrv)
- CWE-522: Insufficiently Protected Credentials
- [CVE-2024-35255](https://github.com/advisories/GHSA-m5vv-6r4h-3vj9)
- CWE-362: Concurrent Execution using Shared Resource with Improper Synchronization ('Race Condition')
> Updated dependency Azure.Identity v1.11.4 because of security issues

- src/NLog.Extensions.AzureBlobStorage/BlobStorageTarget.cs
- src/NLog.Extensions.AzureBlobStorage/NLog.Extensions.AzureBlobStorage.csproj
- src/NLog.Extensions.AzureBlobStorage/README.md
- src/NLog.Extensions.AzureDataTables/DataTablesTarget.cs
- src/NLog.Extensions.AzureDataTables/ICloudTableService.cs
- src/NLog.Extensions.AzureDataTables/NLog.Extensions.AzureDataTables.csproj
- src/NLog.Extensions.AzureDataTables/README.md
- src/NLog.Extensions.AzureEventGrid/EventGridTarget.cs
- src/NLog.Extensions.AzureEventGrid/IEventGridService.cs
- src/NLog.Extensions.AzureEventGrid/NLog.Extensions.AzureEventGrid.csproj
- src/NLog.Extensions.AzureEventGrid/README.md
- src/NLog.Extensions.AzureEventHub/EventHubTarget.cs
- src/NLog.Extensions.AzureEventHub/IEventHubService.cs
- src/NLog.Extensions.AzureEventHub/NLog.Extensions.AzureEventHub.csproj
- src/NLog.Extensions.AzureEventHub/README.md
- src/NLog.Extensions.AzureQueueStorage/ICloudQueueService.cs
- src/NLog.Extensions.AzureQueueStorage/NLog.Extensions.AzureQueueStorage.csproj
- src/NLog.Extensions.AzureQueueStorage/QueueStorageTarget.cs
- src/NLog.Extensions.AzureQueueStorage/README.md
- src/NLog.Extensions.AzureServiceBus/ICloudServiceBus.cs
- src/NLog.Extensions.AzureServiceBus/NLog.Extensions.AzureServiceBus.csproj
- src/NLog.Extensions.AzureServiceBus/README.md
- src/NLog.Extensions.AzureServiceBus/ServiceBusTarget.cs
- test/NLog.Extensions.AzureDataTables.Tests/CloudTableServiceMock.cs
- test/NLog.Extensions.AzureEventGrid.Tests/EventGridServiceMock.cs
- test/NLog.Extensions.AzureEventHub.Tests/EventHubServiceMock.cs
- test/NLog.Extensions.AzureQueueStorage.Tests/CloudQueueServiceMock.cs
- test/NLog.Extensions.AzureServiceBus.Tests/ServiceBusMock.cs
> Added ManagedIdentityClientId + ManagedIdentityResourceId
